spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver    # mariadb의 jdbc 드라이버
    username: root       # 데이터베이스 사용자 ID
    password: //////     # 데이터베이스 사용자 비밀번호
    url: jdbc:mariadb://localhost:3306/subcontract      # 데이터베이스 url
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp